/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCol: typeof import('@ionic/vue')['IonCol']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonDatetime: typeof import('@ionic/vue')['IonDatetime']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonMenuButton: typeof import('@ionic/vue')['IonMenuButton']
    IonMenuToggle: typeof import('@ionic/vue')['IonMenuToggle']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonPopover: typeof import('@ionic/vue')['IonPopover']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToast: typeof import('@ionic/vue')['IonToast']
    IonToggle: typeof import('@ionic/vue')['IonToggle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    Menu: typeof import('./components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysMenu: typeof import('./components/SysMenu.vue')['default']
  }
}
